development:
  adapter: postgresql
  encoding: unicode
  database: bicker_development
  pool: 5
  username: bicker
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bicker_test
  pool: 5
  username: bicker
  password: 